[package]
name = "devmode"
version = "0.1.2"
edition = "2018"
license = "GPL-2.0"
description = "Devmode is a project management utility for developers."
homepage = "https://devmode.edfloreshz.dev/"
documentation = "https://docs.rs/devmode"
repository = "https://github.com/edfloreshz/devmode/"
readme = "README.md"
exclude = [
    ".idea",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33.3", features = ["yaml"] }
anyhow = "1.0.44"
regex = "1.5.4"
walkdir = "2.3.2"
git2 = "0.13.22"
dirs = "3.0.2"
toml = "0.5.8"
colored = "2.0.0"
cmd_lib = "1.1.0"
requestty = "0.1.1"
serde = { version = "1.0.126", features = ["derive"] }
