[package]
name = "devmode"
version = "0.1.0"
edition = "2018"
license = "GPL-2.0"
description = "Devmode is a code management utility for developers."
homepage = "https://devmode.edfloreshz.dev/"
documentation = "https://docs.rs/devmode"
repository = "https://github.com/edfloreshz/devmode/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"