name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        components: rustfmt, clippy
    - run: cd dmd
    - name: Build
      run: cd dmd && cargo build --verbose && cargo clippy && cd ../dmdt && cargo build --verbose && cargo clippy && cd ../dmdlib && cargo build --verbose && cargo clippy
    - name: Run tests
      run: cd dmd && cargo test --verbose && cd ../dmdt && cargo test --verbose && cd ../dmdlib && cargo test --verbose
