name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cd dmd
    - name: rust-clippy-check
      uses: actions-rs/clippy-check@v1.0.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: cd dmd && cargo build --verbose && cd ../dmdt && cargo build --verbose && cd ../dmdlib && cargo build --verbose
    - name: Run tests
      run: cd dmd && cargo test --verbose && cd ../dmdt && cargo test --verbose && cd ../dmdlib && cargo test --verbose
